# This workflow will run the "tools/scraper.py" script once a day, while also
# committing any changes to the repository.

name: Create API Backup

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch: {}

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade --user -r tools/requirements.txt
      - name: Configure git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Run scraper
        id: run_scraper
        continue-on-error: true
        env:
          SERVICE_ID: ${{secrets.REPO_SERVICE_ID}}
        run: |
          python tools/scraper.py

      - name: Commit changes
        if: steps.run_scraper.outcome == 'success'
        continue-on-error: true
        run: |
          git add data/
          git commit -m "Automatic Scraper Update"
          git push origin main
